// @flow

export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CARD = 'ADD_CARD';
export const SORT_CATEGORY_ITEMS = 'SORT_CATEGORY_ITEMS';
export const SWITCH_CATEGORIES = 'SWITCH_CATEGORIES';
